Repository SoomTeum/backend, pull requests merged in 2025-09, with the labels that each got.

#52 [Feat/#42] 나의 여행지 저장 API 구현
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceLikeController.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlaceItemDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlacePageResponseDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlaceResponseDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/entity/UserPlace.java
  src/main/java/com/comma/soomteum/domain/userPlace/repository/UserPlaceRepository.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
Labels: :sparkles: feat

#54 [Refactor/#51] User place, like 로직 리팩토링
  fix_user_place_constraint.sql
  src/main/java/com/comma/soomteum/config/JacksonConfig.java
  src/main/java/com/comma/soomteum/domain/auth/dto/LoginResponseDto.java
  src/main/java/com/comma/soomteum/domain/auth/service/AuthService.java
  src/main/java/com/comma/soomteum/domain/place/entity/Place.java
  src/main/java/com/comma/soomteum/domain/place/repository/PlaceRepository.java
  src/main/java/com/comma/soomteum/domain/place/service/PlaceService.java
  src/main/java/com/comma/soomteum/domain/place/service/TatsCnctrApiCaller.java
  src/main/java/com/comma/soomteum/domain/theme/repository/ThemeRepository.java
  src/main/java/com/comma/soomteum/domain/user/controller/UserController.java
  src/main/java/com/comma/soomteum/domain/user/dto/UserProfileResponseDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceLikeController.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceActionRequestDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlaceItemDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
  src/main/java/com/comma/soomteum/global/response/ErrorCode.java
Labels: 🔧 refactor

#56 Feat/#21 위치기반 관광지 추천 시스템
  src/main/java/com/comma/soomteum/domain/ai/adapter/AiServiceAdapter.java
  src/main/java/com/comma/soomteum/domain/ai/dto/AiRecommendationRequest.java
  src/main/java/com/comma/soomteum/domain/ai/dto/AiRecommendationResponse.java
  src/main/java/com/comma/soomteum/domain/ai/service/AiRecommendationService.java
  src/main/java/com/comma/soomteum/domain/place/controller/PlaceController.java
  src/main/java/com/comma/soomteum/domain/place/dto/TourApiRequestDto.java
  src/main/java/com/comma/soomteum/domain/tour/controller/RecommendPlacesController.java
  src/main/java/com/comma/soomteum/domain/tour/service/RecommendPlacesService.java
  src/test/java/com/comma/soomteum/domain/ai/service/AiRecommendationScoreDubugTest.java
Labels: :sparkles: feat

#58 [Refactor/#55] userPlace like, save 로직 개편
  src/main/java/com/comma/soomteum/domain/place/service/PlaceService.java
  src/main/java/com/comma/soomteum/domain/theme/repository/ThemeRepository.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceLikeController.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceActionRequestDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
Labels: 🔧 refactor

#63 [Feat/#61] 지역 기반 혼잡도 받아오기 추가
  .claude/settings.local.json
  src/main/java/com/comma/soomteum/domain/parking/controller/DebugController.java
  src/main/java/com/comma/soomteum/domain/place/controller/KorService2Controller.java
  src/main/java/com/comma/soomteum/domain/place/service/PlaceDetailIntegratedService.java
  src/main/java/com/comma/soomteum/domain/tour/controller/TourController.java
  src/main/java/com/comma/soomteum/domain/tour/service/TourService.java
Labels: :sparkles: feat

#64 Feat/#59 추천 여행지 혼잡도 랭킹 로직 추가
  src/main/java/com/comma/soomteum/domain/ai/dto/AiRecommendationResponse.java
  src/main/java/com/comma/soomteum/domain/ai/service/AiRecommendationService.java
  src/main/java/com/comma/soomteum/domain/place/dto/TatsCnctrResponse.java
  src/main/java/com/comma/soomteum/domain/tour/service/TourService.java
Labels: :sparkles: feat

#68 [Fix/#67] 여행지 상세 통합 조회 API에서 한적함 등급이 -2로 반환되는 이슈 수정
  src/main/java/com/comma/soomteum/domain/place/service/PlaceDetailIntegratedService.java
Labels: 🐛 fix

#70 [Refactor/#69] TatsCnctrResponseDto에 필드 추가 및 좋아요 개수
  src/main/java/com/comma/soomteum/domain/place/dto/TatsCnctrResponse.java
  src/main/java/com/comma/soomteum/domain/theme/repository/ThemeRepository.java
  src/main/java/com/comma/soomteum/domain/tour/service/TourService.java
Labels: 🔧 refactor

#82 [Feat/#81] 로그인된 사용자 Place 저장 유무 api
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceSaveStatusResponseDto.java
Labels: :sparkles: feat

#85 [fix/#84] 장소 저장/좋아요 로직 개편
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceActionRequestDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
Labels: 🐛 fix

#87 [Fix/#86] 상세 통합 조회 API 강릉 외 지역 불러오는 이슈 수정
  src/main/java/com/comma/soomteum/domain/place/service/PlaceDetailIntegratedService.java
Labels: 🐛 fix

#92 [Fix/#90] 내 저장 목록 조회 API에 여행지 이름 필드 추가
  src/main/java/com/comma/soomteum/domain/place/entity/Place.java
  src/main/java/com/comma/soomteum/domain/place/service/PlaceService.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceLikeController.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/PlaceSaveController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceActionRequestDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlaceItemDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
Labels: 🐛 fix

#93 [Fix/#91] 좋아요 저장 동시 트랜잭션 문제
  src/main/java/com/comma/soomteum/domain/userPlace/dto/PlaceActionRequestDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
Labels: 🐛 fix

#97 [Fix/#96] 지역 코드 매칭 로직 개선
  src/main/java/com/comma/soomteum/domain/place/service/TatsCnctrService.java
  src/main/java/com/comma/soomteum/domain/region/repository/RegionRepository.java
Labels: 🐛 fix

#98 [Fix/#96] 한적함 API 지역 매핑 에러 수정
  src/main/java/com/comma/soomteum/domain/place/dto/KorService2Response.java
  src/main/java/com/comma/soomteum/domain/place/service/TatsCnctrService.java
Labels: 🐛 fix
