Repository SoomTeum/backend, pull requests merged in 2025-08, with the labels that each got.

#15 feat: 이슈, PR 템플릿
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feat

#17 feat/#16: token 테이블 추가
  src/main/java/com/comma/soomteum/domain/token/entity/Token.java
Labels: feat

#19 [Feat/#18] 카카오 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/comma/soomteum/config/JpaAuditingConfig.java
  src/main/java/com/comma/soomteum/config/SecurityConfig.java
  src/main/java/com/comma/soomteum/config/SwaggerConfig.java
  src/main/java/com/comma/soomteum/config/WebConfig.java
  src/main/java/com/comma/soomteum/domain/auth/JwtAuthenticationFilter.java
  src/main/java/com/comma/soomteum/domain/auth/JwtTokenManager.java
  src/main/java/com/comma/soomteum/domain/auth/annotation/LoginUser.java
  src/main/java/com/comma/soomteum/domain/auth/annotation/LoginUserArgumentResolver.java
  src/main/java/com/comma/soomteum/domain/auth/controller/AuthController.java
  src/main/java/com/comma/soomteum/domain/auth/dto/AuthTokenRequestDto.java
  src/main/java/com/comma/soomteum/domain/auth/dto/KakaoTokenRequestDto.java
  src/main/java/com/comma/soomteum/domain/auth/dto/KakaoUserResponseDto.java
  src/main/java/com/comma/soomteum/domain/auth/dto/LoginResponseDto.java
  src/main/java/com/comma/soomteum/domain/auth/service/AuthService.java
  src/main/java/com/comma/soomteum/domain/auth/service/KakaoAuthService.java
  src/main/java/com/comma/soomteum/domain/token/dto/TokenDto.java
  src/main/java/com/comma/soomteum/domain/token/entity/Token.java
  src/main/java/com/comma/soomteum/domain/token/repository/TokenRepository.java
  src/main/java/com/comma/soomteum/domain/user/entity/User.java
  src/main/java/com/comma/soomteum/domain/user/repository/UserRepository.java
Labels: :sparkles: feat

#28 [Feat/#24] JWT 헤더 넣은 후 api 조회시 403 에러
  install-jq-gitbash.sh
  src/main/java/com/comma/soomteum/config/SecurityConfig.java
  src/main/java/com/comma/soomteum/domain/auth/JwtAuthenticationFilter.java
  src/main/java/com/comma/soomteum/domain/auth/JwtTokenManager.java
  src/main/java/com/comma/soomteum/domain/auth/service/AuthService.java
  src/main/java/com/comma/soomteum/domain/place/Controller/KorService2Controller.java
  src/main/java/com/comma/soomteum/domain/token/dto/TokenDto.java
  src/main/java/com/comma/soomteum/domain/token/entity/Token.java
Labels: fix

#30 [feat/#29] 카카오 콜백 구현
  build.gradle
  src/main/java/com/comma/soomteum/config/SwaggerConfig.java
  src/main/java/com/comma/soomteum/domain/auth/controller/AuthController.java
  src/main/java/com/comma/soomteum/domain/auth/dto/DevLoginRequestDto.java
  src/main/java/com/comma/soomteum/domain/auth/dto/KakaoTokenResponseDto.java
  src/main/java/com/comma/soomteum/domain/auth/service/AuthService.java
  src/main/java/com/comma/soomteum/domain/auth/service/KakaoAuthService.java
  src/main/java/com/comma/soomteum/global/response/ErrorCode.java
Labels: :sparkles: feat

#44 [Chore/#43] 깃허브 이슈 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/issue-template-v1.md
  .github/ISSUE_TEMPLATE/issue-template-v2.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs

#49 [Feat/#47] 여행지 좋아요 관련 api 구현
  src/main/java/com/comma/soomteum/domain/auth/annotation/LoginUserArgumentResolver.java
  src/main/java/com/comma/soomteum/domain/place/controller/PlaceController.java
  src/main/java/com/comma/soomteum/domain/place/entity/Place.java
  src/main/java/com/comma/soomteum/domain/place/repository/PlaceRepository.java
  src/main/java/com/comma/soomteum/domain/place/service/PlaceService.java
  src/main/java/com/comma/soomteum/domain/userPlace/controller/UserPlaceController.java
  src/main/java/com/comma/soomteum/domain/userPlace/dto/UserPlaceResponseDto.java
  src/main/java/com/comma/soomteum/domain/userPlace/entity/UserPlace.java
  src/main/java/com/comma/soomteum/domain/userPlace/repository/UserPlaceRepository.java
  src/main/java/com/comma/soomteum/domain/userPlace/service/UserPlaceService.java
  src/main/java/com/comma/soomteum/global/response/ErrorCode.java
Labels: :sparkles: feat
